Update deploy.yaml

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -1,78 +1,84 @@
-name: Provision Infra using Terraform via EC2 
+name: Terraform Infra Provisioning using Ec2
 
 on:
- push:
+  workflow_dispatch:
+    inputs:
+      action:
+        description: 'Choose the Terraform action'
+        required: true
+        default: 'apply'  # Default action is apply
+        type: choice
+        options:
+          - apply
+          - destroy
 permissions:
+  contents: write
   id-token: write
-  contents: read
+ 
 jobs:
-  provision:
-    name: Terraform Infra via EC2
+  lint-and-security:
+    name: Lint and Security Checks
     runs-on: ubuntu-latest
- 
+
     steps:
-      - name: Checkout repo
+      - name: Checkout code
         uses: actions/checkout@v4
- 
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          role-to-assume: ${{ secrets.ROLE }}
-          aws-region: us-east-2
- 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v3
-        with:
-          terraform_version: '1.10.5'
-          
-      - name: Terraform formtat (Create EC2)
-        run: terraform fmt
-        
 
-      - name: Terraform init (Create EC2)
+      - name: Install TFLint
+        run: |
+          wget https://github.com/terraform-linters/tflint/releases/download/v0.50.2/tflint_linux_amd64.zip
+          unzip tflint_linux_amd64.zip
+          sudo mv tflint /usr/local/bin/
+          tflint --version
+
+      - name: Run TFLint
+        run: tflint --init && tflint -f compact
+        working-directory: ./
+
+      - name: Install Checkov
+        run: |
+          pip3 install --upgrade pip
+          pip3 install checkov
+
+      - name: Run Checkov
+        run: checkov -d . --framework terraform --soft-fail
+        working-directory: ./
+  terraform_apply_destroy:
+    runs-on: ubuntu-latest
+    needs: lint-and-security
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: arn:aws:iam::211125325699:role/Demo_Access
+          aws-region: us-east-1
+
+      - name: Set up Terraform
+        uses: hashicorp/setup-terraform@v2.0.3
+        with:
+          terraform_version: ">= 1.12.0"
+
+      - name: Initialize Terraform
         run: terraform init
-        
-      - name: Terraform validate 
-        run: terraform validate 
-
-      - name: Terraform plan (Create EC2)
+      
+      - name: Validate Terraform
+        run: terraform validate
+        working-directory: ./
+      
+      - name: Generate Terraform Plan
         run: terraform plan
-        
-      - name: Install tflint
+        working-directory: ./
+      
+      - name: Perform Action
         run: |
-             curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
-
-      - name: Run tflint with custom config
-        run: |
-          echo "Using custom rules from .tflint.hcl"
-          tflint --config=./.tflint.hcl
-        continue-on-error: true
-      # - name: Install terraform-docs
-      #   run: |
-      #       curl -s https://raw.githubusercontent.com/terraform-docs/terraform-docs/master/scripts/install.sh
- 
-      # # - name: Generate Terraform docs
-      # #   run: terraform-docs markdown . > README.md
- 
-      # # - name: Commit docs
-      # #   if: github.ref == 'refs/heads/main'
-      # #   run: |
-      # #        git config user.name "GitHub Actions"
-      # #        git config user.email "actions@github.com"
-      # #        git add README.md
-      # #        git diff --cached --quiet || git commit -m "Update Terraform docs"
-      # #        git push
-             
-      # - name: Generate terraform docs
-      #   uses: terraform-docs/gh-actions@v1.0.0
-      #   with:
-      #      working-dir: ./modules/vpc
-      #      output-file: README.md
-      #      output-method: replace
-          
-      - name: Terraform Apply (Create EC2)
-        run: terraform apply -auto-approve
-        
-      - name: Terraform destroy (Create EC2)
-        run: terraform destroy -auto-approve
-        
+          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
+            terraform apply -auto-approve
+          elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
+            terraform destroy -auto-approve
+          else
+            echo "Invalid action selected."
+            exit 1
+          fi
